name: Cron Action
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'


jobs:
  promopassagens:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Run PromoPassagens
        run: python promopassagens.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          DESTINATION: ${{ secrets.DESTINATION }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_OWNER: ${{ secrets.TWITTER_OWNER }}
          TWITTER_SLUG: ${{ secrets.TWITTER_SLUG }}
