name: Melhores Destinos
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'


jobs:
  promopassagens:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Run PromoPassagens
        run: python promopassagens.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          DESTINATION: ${{ vars.DESTINATION }}
          URL: https://www.melhoresdestinos.com.br/feed
